### ISSUE TITLE
Add support for Multi-AZ SDDCs with less than 6 hosts

### ISSUE THREAD

**Issue by jpeters-vmw** [vmware/terraform-provider-vmc#127]
### Is your feature request related to a problem? Please describe.

Currently it is required that num_hosts be at least 6 for multi-az SDDCs, however 2 host multi-az SDDCs are now supported.

### Describe the solution you'd like

Modify the requirement for multi-az SDDCs to allow a minimum of 2 hosts instead of 6.

**Comment by dimitarproynov** [comment]
Hi,

The Terraform provider doesn't have any restrictions of the minimum number of hosts in an SDDC (other than num_hosts >= 1).

Any such restrictions are implemented in the VMC service. For the minimum number of hosts per SDDC in MultiAZ there is a configuration property with default value of 4. In your case it may have been changed to 6. Please turn to the VMC support team to change the Org's property.

Since there are no checks regarding the minimum number of hosts in SDDC in terraform provider I'll be closing this issue.

Best Regards,
_Proynov
