### ISSUE TITLE
Not able to create SingleAZ deployment type with 6 min hosts

### ISSUE THREAD

**Issue by samirshaik** [vmware/terraform-provider-vmc#149]
### Describe the bug

Following configuration fails with this error - "Error:  Failed to create SDDC: [Maximum host limit of 4 hosts reached for the cluster. (code)115 ]". After SDDC is created we are able to make this change and re-deploy to add 2 new hosts. This behavior appear buggy.

```
...{
    num_host=6
    deployment_type="SingleAZ"
}
```

### Reproduction steps

```bash
provider "vmc" {
  refresh_token = var.api_token
  org_id = var.org_id
}

data "vmc_connected_accounts" "my_accounts" {
  account_number = var.aws_account_number
}

data "vmc_customer_subnets" "my_subnets" {
  connected_account_id = data.vmc_connected_accounts.my_accounts.id
  region               = var.sddc_region
}

resource "vmc_sddc" "sddc_1" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.vpc_cidr
  num_host            = 6
  provider_type       = "AWS"
  region              = data.vmc_customer_subnets.my_subnets.region
  vxlan_subnet        = var.vxlan_subnet
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type = "SingleAZ"
  sddc_type ="1NODE"
  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }
  microsoft_licensing_config {
   mssql_licensing = "ENABLED"
   windows_licensing = "DISABLED"
  }
}
```
```


### Expected behavior

We should be able to create SingleAZ SDDC with 6 hosts in the first run.

### Additional context

Fails to create SDDC with 6 hosts, but able to add 2 more hosts after SDDC is created.

**Comment by dimitarproynov** [comment]
Hi,

This is actually the default behavior of the SDDC provision flow. For new SDDC there is a configuration property for your Org that controlls the maximum number of hosts per *new* SDDC. The default value is 4. 

I'm really not certain what the VMC folks had in mind with this restriction, but if it is an issue for you, please contact the 
VMC support team and ask them to increase the value of the property that controlls how much hosts you can initially provision with an SDDC for your Organization.

Since this is actually the default behavior of the VMC service and not an issue with the Terraform Provider, I'll be closing this issue.

Best Regards,
_Proynov
