### ISSUE TITLE
Feature Request :  Data Sources - vmc_sddc

### ISSUE THREAD

**Issue by AdrianBegg** [vmware/terraform-provider-vmc#92]
Could consideration please be given to the extension of the provider to include a vmc_sddc data source ? I use the attributes of the SDDC objects in other modules/projects that consume the SDDCs and at the moment have to write a bunch of attributes (e.g. cloudadmin password, vsphere_uri, nsxt_rp_uri, UUID, etc.) to an external store (e.g. AWS Secrets Manager) and then using the aws_secretsmanager data object reading the values when consuming SDDCs in a different project when dynamically generating the objects.

This approach is OK however inefficient (using an external attribute store adds cost and duplicates a stale copy of the data) and makes code readability (passing hardcoded values into template files) when it would be nicer in most cases to just read and return the SDDC object using a data object.

Some example use cases:
* Avoid requirement when calling the vmware/nsxt provider in templates or other projects (for terraforming firewall rules for example) to hardcode host values (could use vmc_sddc datastore to make code cleaner)
* Avoid requirement when using hashicorp/vphere provider in  templates or other projects (for terraforming the vCenter) to use another provider (e.g. AWS Secrets Manager and/or DynamoDB) to store the cloudadmin pwd, user, vSphere URI etc.
* In Cloud Director service when terraforming the environment to be able to retrieve the values without using third party attribute store

Cheers

**Comment by jontyq** [comment]
Hi Adrian,

Couple of comments.  In general, yes a vmc_sddc data source could be a nice thing.  

1.)  It's not too hard to achieve what you want though by simply adding `output`s for the relevant bits of information you need.   This is common practice with Terraform to achieve your ends.  I know you have a list of them, the list is not _that_ extensive. 

E.g., we don't hard-code the NSXT reverse proxy url, we use the output in the SDDC state file to feed the nsxt terraform step.

This excellent blog shows you how to stitch the phases together: https://www.gilles.cloud/2020/02/using-terraform-with-multiple-providers.html
 
2.)  All the information you require is available via the api https://vmc.vmware.com/vmc/api/orgs/${ORG_ID}/sddcs" including cloudadmin password etc.  Since you are already writing orchestration around the Terraform steps, this would be far preferable to storing stuff in some external store - particularly you don't want to go exposing your password etc like that. 

 A little `bash` to get your access token and then call the api, coupled with `jq` to extract the data you need works wonders!

**Comment by AdrianBegg** [comment]
Hi @jontyq,

So writing the attributes out via output variables or using another data provider (I am using the DynamoDB and AWS Secrets Store) is working fine to allow us to address the resources externally and I could write a module to wrap the API call - I guess the main motivation for a creating an vmc_sddc data provider in my view would be;

a) To decouple the terraform workflows which manages the SDDCs from workflows that might consume the objects below (vSphere stack)
b) To allow consumers to address SDDC attributes for objects (using terraform) that were not created by terraform (e.g. SDDC created in an CSP Org by manual process) in a consistent manner; at the moment there is no way using the provider to query existing resources in the Org just to read the attributes
c) Code readability/reusability - if using a module/API calls to achieve this then I would have to support that component going forward and any changes/enhancements to the product in the future

Would be "nice to have"/low priority from my point to make the provider more useful for extending integration with provisioning the components below the vmc_sddc object  (vSphere and NSX-T specifically) but from an implementers perspective I do see value in it.

**Comment by shylasrinivas** [comment]
@AdrianBegg I have added support for new SDDC datasource. Please test it out and let us know if you have further feedback. We have purposefully left passwords out from the datasource due to security concerns. I can add it back based on the outcome of internal discussions.
