### ISSUE TITLE
*internal VMware* SDDC deployment fails with ZeroCloud

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#95]
When  `provider_type       = "ZEROCLOUD"`
there should be  no check around NSX reverse proxy since it doesn't exist.

```
Error: NSX reverse proxy url is required for public IP resource creation
  on main.tf line 30, in resource "vmc_sddc" "sddc_1":
  30: resource "vmc_sddc" "sddc_1" {
```
1.3 is ok
1.4 is ok
1.5 fails

**Comment by shylasrinivas** [comment]
@gchek Please share the config used when you encountered this error. I am not sure I understand why you are trying to create public ip if NSX reverse proxy doesn't exist for zerocloud.

I tested this in 1.4.0 and got the reported error. This behavior is not specific to 1.5.0. 
I also think this check is valid, because public IP cannot be created without NSX reverse proxy url and any attempt to do so without it should fail.

**Comment by gchek** [comment]
See my slack message

**Comment by jontyq** [comment]
Just wanna say: Please give customers ZEROCLOUD!  This would allow us to shake out many bugs in our pipeline and TF code without having to wait 1.5 hours+ every time for a build!

(I know it's not your area, but hey if you can feed it up, many voices etc!)
